contracts/MapleGlobals.sol
contracts/MplRewardsFactory.sol
contracts/StakeLocker.sol

feat: Add/update events

---

flatten.sh

feat: Improve the flattening script by handling the licenses

---

README.md

chore: Add link to audit report in README (SC-1944)

---

contracts/test/Loan.t.sol
contracts/test/PoolClaim.t.sol
contracts/test/PoolDelegate.t.sol
contracts/test/PoolLiquidation.t.sol
contracts/test/PoolLiquidityProvider.t.sol
contracts/test/TestUtil.sol

feat: Refactor Pool tests to use fuzzing (SC-1905)

---

contracts/Pool.sol

chore: Fix infinite allowance issue

---

contracts/CollateralLockerFactory.sol
contracts/DebtLockerFactory.sol
contracts/FundingLockerFactory.sol
contracts/LiquidityLockerFactory.sol
contracts/Loan.sol
contracts/LoanFactory.sol
contracts/MapleGlobals.sol
contracts/MapleTreasury.sol
contracts/MplRewards.sol
contracts/MplRewardsFactory.sol
contracts/Pool.sol
contracts/PoolFactory.sol
contracts/StakeLocker.sol
contracts/StakeLockerFactory.sol
contracts/library/PoolLib.sol
contracts/oracles/ChainlinkOracle.sol
contracts/test/TestUtil.sol
contracts/token/BasicFDT.sol
contracts/token/ExtendedFDT.sol

Rectify event-related issues raised by C4 and and normalize event indexing, cosmetics, and comments code-wide.
Clubhouse: https://app.clubhouse.io/maplefinance/story/2034/maple-core-c4-events-updates
- Comment indicates that FundsWithdrawn event should be emitted only when _withdrawableDividend > 0  (https://github.com/code-423n4/2021-04-maple-findings/issues/96)
- No event is emitted (https://github.com/code-423n4/2021-04-maple-findings/issues/8)
- Missing event for critical operation of setAdmin change for Protocol admin in MapleGlobals.sol (https://github.com/code-423n4/2021-04-maple-findings/issues/38)
- Missing event for critical operation of Pool Delegate validity change in MapleGlobals.sol (https://github.com/code-423n4/2021-04-maple-findings/issues/39)
- Missing event for critical …

chore: C4 event updates and normalization (SC-2034)

---

contracts/Pool.sol
contracts/StakeLocker.sol
contracts/library/PoolLib.sol

chore: Removing TODOs (SC-2042)

---

contracts/StakeLocker.sol
contracts/library/PoolLib.sol
contracts/test/StakeLocker.t.sol

Simplified/Cleaner updateDate logic
https://app.clubhouse.io/maplefinance/story/2074/maple-core-simplified-cleaner-updatedate-logic

refactor: Simplified/Cleaner updateDate logic (SC-2074)

---

contracts/StakeLocker.sol
contracts/test/StakeLocker.t.sol

chore: fix the PD transferFrom restriction in StakeLocker

---

contracts/Pool.sol
contracts/StakeLocker.sol
contracts/interfaces/IPool.sol
contracts/test/PoolDelegate.t.sol
contracts/test/StakeLocker.t.sol
contracts/test/user/PoolDelegate.sol

feat: Remove inconsistency from the auth model

---

contracts/oracles/ChainlinkOracle.sol
contracts/test/ChainLinkOracle.t.sol

Add safety checks in the ChainlinkOracle related to stale data i.e https://github.com/code-423n4/2021-04-maple-findings/issues/82 & fix `setManualPrice()` stuff as well https://github.com/code-423n4/2021-04-maple-findings/issues/85

feat: C4 validations (SC- 2040)

---

contracts/CollateralLockerFactory.sol
contracts/DebtLocker.sol
contracts/DebtLockerFactory.sol
contracts/FundingLockerFactory.sol
contracts/LateFeeCalc.sol
contracts/LiquidityLockerFactory.sol
contracts/Loan.sol
contracts/LoanFactory.sol
contracts/MapleGlobals.sol
contracts/MapleTreasury.sol
contracts/MplRewards.sol
contracts/MplRewardsFactory.sol
contracts/Pool.sol
contracts/PoolFactory.sol
contracts/PremiumCalc.sol
contracts/RepaymentCalc.sol
contracts/StakeLocker.sol
contracts/StakeLockerFactory.sol
contracts/library/LoanLib.sol
contracts/library/PoolLib.sol
contracts/library/Util.sol
contracts/math/SafeMathUint.sol
contracts/oracles/ChainlinkOracle.sol
contracts/token/BasicFDT.sol
contracts/token/ExtendedFDT.sol

Various gas optimizations, including those specified here: https://app.clubhouse.io/maplefinance/story/2038/maple-core-c4-gas-optimizations
chore: Gas Optimization (https://github.com/code-423n4/2021-04-maple-findings/issues/11)
- Unused definition of enum (https://github.com/code-423n4/2021-04-maple-findings/issues/17)
- Using precalculated value in the Pool & Loan contracts (https://github.com/code-423n4/2021-04-maple-findings/issues/75)
- Unused variable (https://github.com/code-423n4/2021-04-maple-findings/issues/78)
refactor: More gas optimizations
- Use local variables to reduce storage access
- Use return variables when legible and possible
- if (exitCase) exit, so that large code can be done unindented, and smaller jumpdest
- --x and ++x are sometimes better, since there is no …

refactor: Gas Optimizations (C4 and other) (SC-2038)

---

contracts/Pool.sol
contracts/library/LoanLib.sol

Addresses https://github.com/code-423n4/2021-04-maple-findings/issues/4

feat: Update `collateralRequiredForDrawdown` conversion approach (SC-2086)

---

contracts/MapleGlobals.sol
contracts/StakeLocker.sol
contracts/library/LoanLib.sol
contracts/library/PoolLib.sol
contracts/test/PoolClaim.t.sol

Addresses https://github.com/code-423n4/2021-04-maple-findings/issues/14

feat: Add explicit parenthesis, remove TODO

---

contracts/test/Gulp.t.sol
contracts/test/PoolDelegate.t.sol
contracts/test/PoolLiquidation.t.sol
contracts/test/TestUtil.sol

refactor: Refactor tests to use $3m of Balancer pool liquidity (SC-2060)

---

contracts/Loan.sol
contracts/library/LoanLib.sol
contracts/test/Calcs.t.sol
contracts/test/PoolClaim.t.sol

Addresses https://github.com/code-423n4/2021-04-maple-findings/issues/112

feat: Add late fees to makeFullPayment (SC-2087)

---

contracts/MapleGlobals.sol
contracts/Pool.sol
contracts/StakeLocker.sol
contracts/interfaces/IMapleGlobals.sol
contracts/interfaces/IStakeLocker.sol
contracts/library/PoolLib.sol
contracts/test/MapleGlobals.t.sol
contracts/test/PoolCustodial.t.sol
contracts/test/StakeLockerCustodial.t.sol
contracts/test/TestUtil.sol
contracts/test/user/Custodian.sol
contracts/test/user/Governor.sol
contracts/test/user/Staker.sol

feat: Add ERC-2258 functionality to StakeLocker (SC-2089)

---

contracts/MapleGlobals.sol
contracts/test/MapleGlobals.t.sol

fix: Prevent investorFee and treasuryFee globals overflow

---

contracts/Loan.sol
contracts/LoanFactory.sol
contracts/MapleGlobals.sol
contracts/MplRewardsFactory.sol
contracts/Pool.sol
contracts/PoolFactory.sol
contracts/PremiumCalc.sol
contracts/RepaymentCalc.sol
contracts/StakeLocker.sol
contracts/library/LoanLib.sol
contracts/library/PoolLib.sol
contracts/oracles/IChainlinkAggregatorV3.sol
contracts/test/PoolDelegate.t.sol
contracts/token/BasicFDT.sol
contracts/token/ExtendedFDT.sol
contracts/token/LoanFDT.sol
contracts/token/StakeLockerFDT.sol

Minor corrections from final review

chore: Minor corrections from final review

---

README.md

feat: Update logo and audit reports in README

---

contracts/test/PoolFDTLosses.t.sol
contracts/test/TestUtil.sol
contracts/test/user/LP.sol

I remove the dapp-cache but again I hit the same problem it is not creating a new cache for me.

feat: Add dedicated interest/loss PoolFDT fuzz testing (SC-2051)

---

test.sh

Added arguments for local testing:
`-t TEST_NAME` to specify the test
`-b 0` to forgo building
`-r X` to specify the number of fuzz runs 
- Added arguments for local testing

feat: Test Script Arguments

---

.gitignore
flatten.sh
flattened-contracts/ChainlinkOracle.sol
flattened-contracts/CollateralLocker.sol
flattened-contracts/CollateralLockerFactory.sol
flattened-contracts/DebtLocker.sol
flattened-contracts/DebtLockerFactory.sol
flattened-contracts/FundingLocker.sol
flattened-contracts/FundingLockerFactory.sol
flattened-contracts/IChainlinkAggregatorV3.sol
flattened-contracts/LateFeeCalc.sol
flattened-contracts/LiquidityLocker.sol
flattened-contracts/LiquidityLockerFactory.sol
flattened-contracts/Loan.sol
flattened-contracts/LoanFactory.sol
flattened-contracts/LoanLib.sol
flattened-contracts/MapleGlobals.sol
flattened-contracts/MapleTreasury.sol
flattened-contracts/MplRewards.sol
flattened-contracts/MplRewardsFactory.sol
flattened-contracts/Pool.sol
flattened-contracts/PoolFactory.sol
flattened-contracts/PoolLib.sol
flattened-contracts/PremiumCalc.sol
flattened-contracts/RepaymentCalc.sol
flattened-contracts/StakeLocker.sol
flattened-contracts/StakeLockerFactory.sol
flattened-contracts/UsdOracle.sol
flattened-contracts/Util.sol

Committed flattened contracts and cleaned up flatennign script outputs
Committed flattened contracts and cleaned up flatennign script outputs

feat: Committed Flattened Contracts
